### ISSUE TITLE
SPIR-V shaders support?

### ISSUE THREAD

**Issue by L2NE-dev** [GPUOpen-LibrariesAndSDKs/V-EZ#1]
Hello. I want ask question about shaders: have V-EZ support of SPIR-V, only only GLSL directly? ~~I planned to port our renderer host for V-EZ.~~ Very interest... 
Also, will have C++ (V-EZ-Hpp) version?

**Comment by soconne** [comment]
SPIR-V is supported.  You simply set VkShaderModuleCreateInfo::pCode to the SPIRV binary data with VkShaderModuleCreateInfo::codeSize equal to the size in bytes.  See the documentation for more details.
https://gpuopen-librariesandsdks.github.io/V-EZ/#_shader_modules
