### ISSUE TITLE
Validation layer errors in samples

### ISSUE THREAD

**Issue by Euxiniar** [GPUOpen-LibrariesAndSDKs/V-EZ#12]
Hello! 
I'm very interested in your work, so I took a look at the examples, and it seems they all generate errors on my pc. 
The line 186 of simpleQuad.cpp generates these two errors:
`VUID-VkMappedMemoryRange-size-01390(ERROR / SPEC): msgNum: 203426524 - vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x18, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The spec valid usage text states 'If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)`
and
` Objects: 1
       [0] 0x4, type: 8, name: (null) Validation(ERROR): msg_code: 203426524:  [ VUID-VkMappedMemoryRange-size-01390 ]  [ VUID-VkMappedMemoryRange-size-01390 ] Object: 0x4 (Type = 8) | vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x18, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The spec valid usage text states 'If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)`

After that, the line 339 generate these errors:
`VUID-VkSubpassDependency-dstAccessMask-00869(ERROR / SPEC): msgNum: 333448906 - CreateRenderPass: pDependencies[0].dstAccessMask (0x100) is not supported by dstStageMask (0x2000). The spec valid usage text states 'Any access flag included in dstAccessMask must be supported by one of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkSubpassDependency-dstAccessMask-00869)`
,
`Objects: 1
       [0] 0x0, type: 0, name: (null)
Validation(ERROR): msg_code: 333448906:  [ VUID-VkSubpassDependency-dstAccessMask-00869 ]  [ VUID-VkSubpassDependency-dstAccessMask-00869 ] Object: VK_NULL_HANDLE (Type = 0) | CreateRenderPass: pDependencies[0].dstAccessMask (0x100) is not supported by dstStageMask (0x2000). The spec valid usage text states 'Any access flag included in dstAccessMask must be supported by one of the pipeline stages in dstStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkSubpassDependency-dstAccessMask-00869)`
,
`VUID-VkSubpassDependency-srcAccessMask-00868(ERROR / SPEC): msgNum: 333448904 - CreateRenderPass: pDependencies[1].srcAccessMask (0x100) is not supported by srcStageMask (0x2000). The spec valid usage text states 'Any access flag included in srcAccessMask must be supported by one of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkSubpassDependency-srcAccessMask-00868)`
and
`Objects: 1
       [0] 0x0, type: 0, name: (null)
Validation(ERROR): msg_code: 333448904:  [ VUID-VkSubpassDependency-srcAccessMask-00868 ]  [ VUID-VkSubpassDependency-srcAccessMask-00868 ] Object: VK_NULL_HANDLE (Type = 0) | CreateRenderPass: pDependencies[1].srcAccessMask (0x100) is not supported by srcStageMask (0x2000). The spec valid usage text states 'Any access flag included in srcAccessMask must be supported by one of the pipeline stages in srcStageMask, as specified in the table of supported access types.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkSubpassDependency-srcAccessMask-00868)`

Note that at the end, the SimpleQuad window finally launches.

I hope it can help improve your library. Thx 😄

**Comment by soconne** [comment]
This has been fixed and will be included in the upcoming open source release of V-EZ.  The source should be live in the next week or two.
