### ISSUE TITLE
Interfacing and interoperability with VMA and plain Vulkan API (1.1.77)?

### ISSUE THREAD

**Issue by L2NE-dev** [GPUOpen-LibrariesAndSDKs/V-EZ#13]
I planned to make our library fully compatible with V-EZ, so I want suggest to add interfacing of memory allocator (VMA) and interoperability with plain Vulkan API.

**Comment by soconne** [comment]
Internally V-EZ already uses VMA.  If you want to use a custom memory allocator, you already can.  See the VulkanMemory sample.
https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ/tree/master/Samples/VulkanMemory

Interoperability with plain Vulkan API is described in the documentation.
https://gpuopen-librariesandsdks.github.io/V-EZ/#_native_vulkan_calls
