### ISSUE TITLE
Typo in documentation example

### ISSUE THREAD

**Issue by kyle-marshall** [GPUOpen-LibrariesAndSDKs/V-EZ#14]
Section 1: Putting it all together, the final example:
line 81: 
VkDeviceCreateInfo deviceCreateInfo = {};
should be
VezDeviceCreateInfo deviceCreateInfo = {};

**Comment by kyle-marshall** [comment]
sorry, I didn't see this was already open already open my bad for spamming you!

**Comment by soconne** [comment]
Fixed in e982a3f72bd18dcd5c2374de12d0a832621d2d74
