### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by ccoors** [GPUOpen-LibrariesAndSDKs/V-EZ#17]
As most other GPUOpen-LibrariesAndSDKs are MIT I guess it will be MIT, but having legal assurance would be nice.

**Comment by xezno** [comment]
The license file is already located within several source files (e.g. https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ/blob/master/Source/VEZ_ext.cpp#L1-L21) but it would definitely be ideal to have a separate file for it.

**Comment by soconne** [comment]
Added.  Thanks.
