### ISSUE TITLE
Linux binaries, please!

### ISSUE THREAD

**Issue by ghost** [GPUOpen-LibrariesAndSDKs/V-EZ#2]
Can't wait to try it out with AMDVLK

**Comment by oscarbg** [comment]
+1

**Comment by soconne** [comment]
Linux is coming soon.  The priority for this first beta release given our target ISVs was Windows.

**Comment by procedural** [comment]
@soconne Just a question, why you target CAD ISVs specifically when easy Vulkan mode would benefit everyone who simply tries to transition to Vulkan from OpenGL 4.5, for example?

**Comment by soconne** [comment]
Version 1.1.0 now includes Linux binaries.
