### ISSUE TITLE
Please add support for disabling vsync, having access to the compiled spirv src and reflection on ubo members

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#22]
Hello folks,
first things first: Awesome lib! I love it so far.

1.) VSync
I really need to disable vsync but i really don't want to mess with the vez code myself if i don't have to.
I recognized there is a function "vezDeviceSetVSync", which unfortunately just returns that the feature is not present yet. Could you please add support for it?

2.) Compiling glsl
Because compiling glsl is terrible slow in debug mode with vez (i did it before myself with shaderc, that was WAY faster in debug), i suggest a function like "vezCompileGLSL(device, info, spv)", which returns the compiled spirv-code, so its able to dump it on disk and read it later.

3.) Reflection on ubo members
This is probably a must have. The information for all the uniform buffer members is simply not parsed, only the whole ubo size is computed. It would be nice to have access to all the members names and types in a ubo. SPIRV-Cross supports it and i had it already implemented before i decided to switch using vez instead of doing everything from scratch

All these points shouldn't take to much time for somebody who's familiar with the code.
If you can't afford time for it i will do it myself after i have done everything else, but i'm also very short on time right now. (Writing my Master Thesis)

Thanks and have a great day!
SH

**Comment by soconne** [comment]
1. Just fixed this with 1f8e9b2c25fe0763c5b354fab398d95c2bc71a5b

2. Added a new function called vezGetShaderModuleBinary 0884906da42d94d20d4e1e182a969ee1b8433e5c.  Please keep in mind for offline compilation, its easier to simply use Khronos's glslangValidator tool.

3. I created a new ticket for this #24
