### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by YaLTeR** [GPUOpen-LibrariesAndSDKs/V-EZ#23]
https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ/blob/e982a3f72bd18dcd5c2374de12d0a832621d2d74/Docs/AsciiDoctor/Initialization.txt#L70
I believe this should be `vezGetPhysicalDeviceProperties`.

**Comment by codecnotsupported** [comment]
If you don't mind hijacking your issue on a other documentation related issue.
#11 was closed but not fixed.

**Comment by soconne** [comment]
Fixed in 8a3302836a33bb5abd0ec2b7cb7b7d6c750e4a42
