### ISSUE TITLE
Disabling vsync does not work on surfaces who doesn't support immediate mode

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#25]
So as the title already states, a fix for this is using the MAILBOX mode if available.

I slightly modified the code in swapchain.cpp:
`
static VkPresentModeKHR ChooseSwapPresentMode(const std::vector<VkPresentModeKHR>& availablePresentModes, const std::vector<VkPresentModeKHR>& desiredModes)
    {
        for (auto& desiredMode : desiredModes)
        {
            for (const auto& availablePresentMode : availablePresentModes)
            {
                if (desiredMode == availablePresentMode)
                    return desiredMode;
            }
        }
        if (availablePresentModes.size() > 0) return availablePresentModes[0];
        else return VK_PRESENT_MODE_FIFO_KHR;
    }
`

And using it this way:
`std::vector<VkPresentModeKHR> desiredModes;
        if (m_vsyncEnabled)
            desiredModes = { VK_PRESENT_MODE_FIFO_KHR };
        else 
            desiredModes = { VK_PRESENT_MODE_MAILBOX_KHR, VK_PRESENT_MODE_IMMEDIATE_KHR };
        auto presentMode = ChooseSwapPresentMode(m_swapchainSupport.presentModes, desiredModes);
        // Determine the total number of images required.
        uint32_t imageCount = m_swapchainSupport.capabilities.minImageCount + 1;
        if (presentMode == VK_PRESENT_MODE_MAILBOX_KHR) // Try to use tripple buffering with mailbox mode
            imageCount = 3;`

Unfortunately i have no idea how i can make a pull request, otherwise i would have done it. Sorry!

**Comment by soconne** [comment]
What platform and hardware are you using?

**Comment by SilvanVR** [comment]
Windows 10 with the NVIDIA Geforce GTX 1070

**Comment by soconne** [comment]
I'll try to reproduce on my end as this seems like it could be a bug in NVIDIA's driver when using FIFO mode.

**Comment by SilvanVR** [comment]
Thanks soconne,
i have another question. Is it possible to use the validation layers effectively when using vez? I have them enabled, but because vez is built as an dll i guess they are not working properly.

**Comment by soconne** [comment]
If you enable the validation layers the same way they’re enabled in the examples it should work.  I’ve had problems with them when installing a new Vulkan SDK over an existing version.  Uninstalling all Vulkan SDKs and then reinstalling only the latest has fixed the issue for me in the past.

**Comment by SilvanVR** [comment]
Nope they doesn't work for me, even though i reinstalled 3x with different versions.
I had VezFramebufferCreateInfo.layers set to 0, which i spent several hours of debugging trying to figure out what's wrong... xD

**Comment by SilvanVR** [comment]
VK_PRESENT_MODE_FIFO_RELAXED_KHR  does not disable vsync. As far as i understand it, it stills waits for every vsync cycle to update the screen, but with the exception if there's not an image in the queue, meaning the application might be too slow, a new request will be displayed immediately, resulting in visible tearing.
I need to measure the speed of my application, but it's not possible with FIFO_RELAXED.
Unfortunately my gpu doesn't support immediate mode anymore (it did a while ago), so i have to use VK_PRESENT_MODE_MAILBOX_KHR. Please give me an option to use this mode (preferable with tripple buffering). In my opinion the VK_PRESENT_MODE_MAILBOX_KHR is the best mode (with tripple buffering) anyway on desktop.

**Comment by soconne** [comment]
Rather than explicitly exposing a minimum image count in the API, I have added the tripleBuffer field to VezSwapchainCreateInfo.  I have also fixed the issue where MAILBOX was not being used for disabled vsync.  Let me know if this fixes your issue.

**Comment by SilvanVR** [comment]
Thanks and yea i think it would if you would have been commited the header file (Swapchain.h) aswell xD I checked the commit, you just changed Swapchain.cpp ;-)

// Offtopic
How long do you think it will take to add suport for individual ubo/ssbo members? I'm at a point where i really need it, otherwise i can't continue. I`ll do it myself if you have no time, but of course i prefer an official solution. :-)

**Comment by soconne** [comment]
VEZ.h was missing from the commit.  It's now in.
