### ISSUE TITLE
Error in StreamDecoder.cpp Line 1017

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#28]
So i tried to debug my engine with render-doc and i recognized that render-doc reports my main-pass as an "depth-only pass". The reason for this is that i had the same output-name in two different shaders (vertex + fragment). Because of that VEZ has internally a VezPipelineResource struct with the stage 17 (Vertex+Fragment). This causes inadvertently in StreamDecoder.cpp Line 1017 to fail the if-statement:
```
if (resource.stages == VK_SHADER_STAGE_FRAGMENT_BIT && resource.resourceType == VEZ_PIPELINE_RESOURCE_TYPE_OUTPUT)
// Add output attachment index and more...
```

I'm not exactly sure how the VezPipelineResource struct is build, so it recognizes same outputs with the same name as equal even if two shaders are clearly distinct. I guess an easy fix would be to test:
`resource.stages & VK_SHADER_STAGE_FRAGMENT_BIT `

**Comment by soconne** [comment]
You are correct this is a bug.  I will fix it correctly as reusing the same name across shader stages should produce distinct entries within the array of VezPipelineResource objects generated.

**Comment by soconne** [comment]
Your output variables are bound to different binding or location indices, correct?

**Comment by SilvanVR** [comment]
No they're equal. Here are my shaders:
```
#shader vertex

#include "/engine/shaders/includes/vulkan/engineVS.glsl"

layout (location = 0) in vec3 VERTEX_POSITION;
layout (location = 1) in vec4 VERTEX_COLOR;

layout (location = 0) out vec4 outColor;

void main()
{
	outColor = VERTEX_COLOR;
	gl_Position = TO_CLIP_SPACE( VERTEX_POSITION );
}
```
And the fragment shader:
```
// ----------------------------------------------
#shader fragment

#include "/engine/shaders/includes/vulkan/engineFS.glsl"

layout (location = 0) out vec4 outColor;

void main()
{
	outColor = vec4(1,0,1,1);
}
```
Both shaders are from different pipelines i.e. the vertex does not belong to this fragment shader!

**Comment by soconne** [comment]
It is the first pipeline (vertex shader only) that's being reported as depth only?  Does it have an accompanying fragment shader?  If these are different pipelines it's not clear why there would be a naming conflict between the declarations for outColor.

**Comment by SilvanVR** [comment]
Yes it is the first one. My main pass renders into an offscreen fbo, in this case just one draw-call using these shaders:
```
#include "/engine/shaders/includes/vulkan/engineVS.glsl"

layout (location = 0) in vec3 VERTEX_POSITION;
layout (location = 1) in vec4 VERTEX_COLOR;

layout (location = 0) out vec4 outColor;

void main()
{
	outColor = VERTEX_COLOR;
	gl_Position = TO_CLIP_SPACE( VERTEX_POSITION );
}

// ----------------------------------------------
#shader fragment

#include "/engine/shaders/includes/vulkan/engineFS.glsl"

layout (location = 0) in vec4 inColor;
layout (location = 0) out vec4 outColor;

void main()
{
	outColor = inColor;
}
```
The next pass renders a fullscreen-quad to the swapchain-image, which uses these two shaders:
```
#shader vertex

#include "/engine/shaders/includes/vulkan/version.glsl"

layout (location = 0) out vec2 outUV;

void main()
{
	outUV = vec2((gl_VertexIndex << 1) & 2, gl_VertexIndex & 2);
	gl_Position = vec4(outUV * 2.0f - 1.0f, 0.0f, 1.0f);
}

// ----------------------------------------------
#shader fragment

#include "/engine/shaders/includes/vulkan/version.glsl"

// In data
layout (location = 0) in vec2 inUV;

// Out data
layout (location = 0) out vec4 outColor;

// Descriptor-Sets
layout (set = 0, binding = 0) uniform sampler2D _Input;

void main()
{
	outColor = texture(_Input, inUV);
}
```
Here is my render-doc replay: https://ufile.io/tufby

**Comment by soconne** [comment]
Fixed and tested on my end.  Let me know if you still experience the problem.
