### ISSUE TITLE
!!!! Binding subsequent buffers via "vezCmdBindBuffer" doesn't work

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#29]
And found another bug :D
If you bind several buffers via "vezCmdBindBuffer" all descriptor-set bindings get the same "streamposition" which causes only the first buffer to be bound in StreamDecoder.cpp Line 172:

```
            // Check to see if there are any descriptor set bindings to be inserted.
            if (nextDescriptorSetBinding != encoder.GetDescriptorSetBindings().cend())
            {
                // The next descriptor set binding's stream position must be equal to the current read position.
                if (nextDescriptorSetBinding->streamPosition == streamPosition)
                {
                    // Bind the descriptor set.
                    vkCmdBindDescriptorSets(commandBuffer.GetHandle(), nextDescriptorSetBinding->bindPoint, nextDescriptorSetBinding->pipelineLayout,
                        nextDescriptorSetBinding->setIndex, 1, &nextDescriptorSetBinding->descriptorSet, 0, nullptr);

                    // Move to the next descriptor set binding in the list.
                    ++nextDescriptorSetBinding;
                }
            }
```
Every descriptor-set binding has the same stream-position:
![descriptor_sets](https://user-images.githubusercontent.com/9498114/44877181-748f5f80-aca3-11e8-8d7b-5b5da77a6590.png)

This should be fixed ASAP, because it prevents to bind any subsequent descriptor-sets, because the "nextDescriptorSetBinding"-variable points to the next descriptor-set with the same stream-position. Because the decoder continues to read from the stream the "nextDescriptorSetBinding"-variable is stuck forever.

**Comment by soconne** [comment]
Can you share the snippet of application code where you're calling vezCmdBindBuffer?  Do these calls all belong to the same draw or different draw calls?  If they're for the same draw call (or dispatch) and they're being called for different binding points, only a single descriptor set should be created.

**Comment by SilvanVR** [comment]
My high level code looks like this:
```
m_globalBuffer->bind(); // Set 0, Binding 0
m_cameraBuffer->bind(); // Set 1, Binding 0
m_lightBuffer->bind(); // Set 2, Binding 0
```
which calls this 
```
void MappedUniformBuffer::bind()
{
    flush(); // Just updates gpu buffer
    g_vulkan.ctx.SetBuffer( m_GPUBuffer.buffer, m_bufferInfo.getBindingSet(), m_bufferInfo.getBindingSlot() );
}
```
which does this:
```
void Context::SetBuffer( VkBuffer buffer, U32 set, U32 binding )
{
    vezCmdBindBuffer( curDrawCmd(), buffer, 0, VK_WHOLE_SIZE, set, binding, 0 );
}
```
In my current test scene i have only one draw-call.
The buffers are in different sets, meaning there should be different descriptor-sets created, but this is not the case. but yea i just realised that i can actually have them all in one set, but still binding subsequently different sets seems to be buggy.

**Comment by soconne** [comment]
Ah thank you, this clears it up.  This is definitely a bug when binding across different sets.  I will fix it immediately.

**Comment by soconne** [comment]
Fix is in.  I tested on my end with 3 set indices and it works.  Let me know if you still have trouble with your code.
