### ISSUE TITLE
Specifying the format of shader resources

### ISSUE THREAD

**Issue by Warpten** [GPUOpen-LibrariesAndSDKs/V-EZ#31]
Currently, given `layout (location = 2) in vec4 inColor;`, the library generates a binding that expects the user to pass a `float[4]`. However, I'm using ImGui, which sends text color using packed colors as `u8[4]`, where each byte is a color component.

This can be seen in PipelineCache.cpp:206:

```cpp
                case VEZ_PIPELINE_RESOURCE_BASE_TYPE_FLOAT:
                    typeSize = sizeof(float);
                    if (input.vecSize == 1) attributeDescription.format = VK_FORMAT_R32_SFLOAT;
                    else if (input.vecSize == 2) attributeDescription.format = VK_FORMAT_R32G32_SFLOAT;
                    else if (input.vecSize == 3) attributeDescription.format = VK_FORMAT_R32G32B32_SFLOAT;
                    else if (input.vecSize == 4) attributeDescription.format = VK_FORMAT_R32G32B32A32_SFLOAT;
                    break;
```

as well as in the spirv reflection loader.

I understand that this library is aimed to helping users kickstart their Vulkan experience, but some flexibility here would be nice.

**Comment by soconne** [comment]
See the documentation section about vertex input formats.
https://gpuopen-librariesandsdks.github.io/V-EZ/#_vertex_input_formats

**Comment by Warpten** [comment]
Oops, this needs to be done at the command buffer level in V-EZ, my bad!

[EDIT] Sorry, was looking at it in the debugger while you replied

**Comment by soconne** [comment]
I’m certainly open to suggestions on a better interface for handling it.  Making it 100% ad-hoc would make the backend more complicated when generating a pipeline state hash.  Creating a vertex input format object up front solves this issue.
