### ISSUE TITLE
Error when binding textures with descriptor sets

### ISSUE THREAD

**Issue by Warpten** [GPUOpen-LibrariesAndSDKs/V-EZ#32]
In StreamEncoder.cpp:952:

```cpp
dsWrite.pImageInfo = reinterpret_cast<const VkDescriptorImageInfo*>(imageInfos.size());
```

This should probably be
```cpp
dsWrite.pImageInfo = imageInfos.data();
```

Since neither size() nor the cast (**especially** the cast) make sense.

**Comment by Warpten** [comment]
I should go sleep.

**Comment by soconne** [comment]
Was this not a real bug?

**Comment by Warpten** [comment]
No - pImageInfo is later corrected with a series of `reinterpret_cast`s. This looks like it could maybe be however simplified to avoid the extra loop, but I was too tired to check.
