### ISSUE TITLE
Wrong .vecsize for matrices

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#34]
The .vecsize field for VezMemberInfo (i guess for VezPipelineResource aswell) is 4 for matrices which should be 16 in this case, because there is no other field which specifies the length for an vector.
This way a real vec4 in hlsl has also a vecsize of 4 and is indistinguishable from an matrix except for the size field. But to tell them apart by inspecting the size field seems rather hacky.

**Comment by soconne** [comment]
I have added a *columns* field to VezMemberInfo.  When iterating over reflection data in SPIRV-Cross, the vecSize field represents only the size of vectors.  A matrix is treated as an array of vec4 values.  The columns field in this case is 4.  I have also added the *columns* field to VezPipelineResource for the case of vertex attribute inputs and outputs.
