### ISSUE TITLE
No support for VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#36]
So tried my engine on my laptop and the weird thing is validation layers are working there, but not on my desktop pc... 
Anyway, had a couple validation complains. One of them is that it's not possible to create an ImageView with VK_IMAGE_VIEW_TYPE_CUBE or VK_IMAGE_VIEW_TYPE_CUBE_ARRAY because there is no way to create the image with the VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT flag (there is no flag field in VezImageCreateInfo).

**Comment by soconne** [comment]
I will add support for this.
