### ISSUE TITLE
VR with Oculus SDK not possible with V-EZ

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#42]
V-EZ does has a Wrapper for the standard vulkan swapchain to work with images/views created via vezCreateImage and vezCreateImageView.
Unfortunately the OculusSDK has its own Swapchain and gives only access to their VkImage's via
```
VkImage image;
ovr_GetTextureSwapChainBufferVk( session, m_swapChain, i, &image );

// Can't create an VkImageView with vezCreateImageView() because image was not created via vezCreateImage()
```
I need a way to use the VkImage returned from the oculus sdk in v-ez.

**Comment by soconne** [comment]
See the function vezImportVkImage in VEZ_ext.h.  You can import the VkImage from the Oculus SDK this way then create a VkImageView from it using V-EZ.
