### ISSUE TITLE
Setting dynamic states through pipeline states effectively does nothing

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#44]
Yea i'm sure you know about it. Setting things like depthBias etc. which are also dynamic states does nothing, because all dynamic states are enabled by default:
```
VezRasterizationState rzState;
 rzState.depthBiasConstantFactor = 1.0f;
 rzState.depthBiasClamp = 1.0f;
 rzState.depthBiasSlopeFactor = 1.0f;
```
All fields above are ignored because the dynamic state with the default values is set. Either update the dynamic state with the values above if no command for setting it was recorded or remove these fields completely.

**Comment by soconne** [comment]
Good catch.  Calling vezCmdSetDepthBias does override the default dynamic state values.  These fields in VezRasterizationState may be able to be removed.  I'll need to look it over and remember if there was a reason they were originally included.

**Comment by SilvanVR** [comment]
Keep in mind that there are probably more than just the depth bias stuff above. You should check every dynamic state and whether there is a field in a pipeline struct.
