### ISSUE TITLE
vezImportVkImage

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#46]
V-EZ needs a function to remove the object implementation manually, if an image was imported.
Problem is when i restart my engine V-EZ has still the old object implementation and crashes because it retrieves the old handle and not the new one.

**Comment by soconne** [comment]
Thanks for pointing this out.  I'll implement a fix.

**Comment by SilvanVR** [comment]
vezRemoveImportedVkImage is missing in VEZ.def
