### ISSUE TITLE
Image layout issues

### ISSUE THREAD

**Issue by SilvanVR** [GPUOpen-LibrariesAndSDKs/V-EZ#48]
I get a lot of layout issues reported from the validation layers:
![layout_issue_0](https://user-images.githubusercontent.com/9498114/46432513-bd2cb380-c74e-11e8-8c77-c09516cc9fca.png)
![layout_issue_1](https://user-images.githubusercontent.com/9498114/46432520-bf8f0d80-c74e-11e8-9804-8847e2a453e7.png)
![layout_issue_2](https://user-images.githubusercontent.com/9498114/46432820-74292f00-c74f-11e8-931f-6f95e953bc9a.png)
My images have a lot of usage flags. Maybe this confuses V-EZ somehow?

**Comment by soconne** [comment]
Try pulling the latest commit I pushed this morning.  It may fix these issues.

**Comment by SilvanVR** [comment]
Seems to be fixed!
