### ISSUE TITLE
Instancing example?

### ISSUE THREAD

**Issue by manhnt9** [GPUOpen-LibrariesAndSDKs/V-EZ#49]
I'm implementing muti-draw indirect with V-EZ and stuck at binding instance data.
Do you have any suggestions?

**Comment by soconne** [comment]
Could you elaborate?  Do you mean you have secondary buffers with meta data you need to access in the shader on a per instance basis?  In the shader you have access to gl_InstanceIndex.  That should be enough to read from your buffers.

**Comment by manhnt9** [comment]
I'm replicating this example using V-EZ: https://github.com/SaschaWillems/Vulkan/tree/master/examples/indirectdraw

In fact, I want multi-draw indirect to be default in my engine.
Currently I'm testing with single triangle drawing, trying to make that an instance, create indirect commands for it, ...

Like so:

```cpp
void CVulkanDriver::buildIndirectCommands()
{
  IndirectCommands.clear();
  
  constexpr int OBJECT_INSTANCE_COUNT = 1;

  // Create on indirect command for each mesh in the scene
  uint32_t m = 0;
  ObjectCount = 0;
  auto smgr = std::dynamic_pointer_cast<scene::CSceneManager>(Device.getSceneManager());
  for (const auto& node : smgr->getSceneNodeList(CurrentPass))
  {
    auto n = std::dynamic_pointer_cast<scene::IMeshSceneNode>(node);
    auto& mesh = n->getMesh();
    auto& meshBuffer = mesh->getMeshBuffer(0);
    VkDrawIndexedIndirectCommand indirectCmd{};
    indirectCmd.instanceCount = OBJECT_INSTANCE_COUNT;
    indirectCmd.firstInstance = m * OBJECT_INSTANCE_COUNT;
    indirectCmd.firstIndex = 0;
    indirectCmd.indexCount = meshBuffer.getIndexCount();
    ObjectCount += indirectCmd.instanceCount;
    IndirectCommands.push_back(indirectCmd);
    m++;
  }

  IndirectDrawCount = static_cast<uint32_t>(IndirectCommands.size());

  saga::vk::Buffer stagingBuffer;
  auto result = vk::createBuffer(VKDevice, MemoryProperties,
    VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
    &stagingBuffer,
    IndirectCommands.size() * sizeof(VkDrawIndexedIndirectCommand),
    IndirectCommands.data()
  );

  result = createBuffer(VKDevice, MemoryProperties,
    VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
    &IndirectCommandBuffer,
    stagingBuffer.size
  );

  vk::copyBuffer(&stagingBuffer, &IndirectCommandBuffer);

  stagingBuffer.destroy();
}

void CVulkanDriver::buildIndirectData()
{
  std::vector<InstanceData> instanceData;
  instanceData.resize(ObjectCount);

  auto smgr = std::dynamic_pointer_cast<scene::CSceneManager>(Device.getSceneManager());
  uint32_t i = 0;
  for (const auto& node : smgr->getSceneNodeList(CurrentPass))
  {
    instanceData[i++].pos = node->getPosition();
  }

  vk::Buffer stagingBuffer;
  auto result = createBuffer(VKDevice, MemoryProperties,
    VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
    VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
    &stagingBuffer,
    instanceData.size() * sizeof(InstanceData),
    instanceData.data()
  );

  result = vk::createBuffer(VKDevice, MemoryProperties,
    VK_BUFFER_USAGE_VERTEX_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
    VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT,
    &InstanceBuffer,
    stagingBuffer.size
  );

  vk::copyBuffer(&stagingBuffer, &InstanceBuffer);

  stagingBuffer.destroy();
}
```

I'm confused at line 213 of [example](https://github.com/SaschaWillems/Vulkan/tree/master/examples/indirectdraw) about how can I bind instance data to a vertex buffer like that.
```cpp
// Binding point 1 : Instance data buffer
vkCmdBindVertexBuffers(drawCmdBuffers[i], INSTANCE_BUFFER_BIND_ID, 1, &instanceBuffer.buffer, offsets);

```

**Comment by soconne** [comment]
In V-EZ (very similar to Vulkan) you'd need to define the vertex attribute descriptions and bindings, in particular the inputRate field.  Calling vkCmdBindVertexBuffers is just a way to associate a particular buffer with a location within your shaders.   There are other Vulkan examples showing how to do this.
https://github.com/GameTechDev/stardust_vulkan

But I can add an instancing sample to my next update to V-EZ if that helps.

**Comment by manhnt9** [comment]
I'm playing around with vertex inputs currently, so I think you could give me some more time to figure it out.
Right now I see that instance data is merely a buffer to pass for a shader, not for the pipeline or the driver to draw.

I would be very interested in studying samples related to high performance rendering: multi-threaded command buffers generation (***), V-EZ's best practices, etc ...

**Comment by manhnt9** [comment]
Hi @soconne, Please consider adding an instancing example. Thank you.
