### ISSUE TITLE
Give the EZ versions of things a proper prefix so Vulkan conflicts are removed

### ISSUE THREAD

**Issue by marti4d** [GPUOpen-LibrariesAndSDKs/V-EZ#5]
Currently this library does not allow linking alongside with the Vulkan static library because the  functions are named the same. Why do things this way? Why not just prefix the functions with something like "Vez" so there is no conflict with the normal Vulkan functions?

Ditto with the header files - Why re-define all the stuff that's already defined in `vulkan.h`? Why not just use `vulkan.h` directly and add whatever stuff you need to, perhaps prefixed?

I think these two limitations (can't use vulkan.h in same source file, can't link vulkan.lib) would be a showstopper for many people who would be considering using this middleware. I would be curious to hear what the rationale is for such a design choice?

**Comment by soconne** [comment]
Please see the Vulkan Compatibility section of the documentation.
https://gpuopen-librariesandsdks.github.io/V-EZ/#_vulkan_compatibility

If an application wishes to link against vulkan-1.lib, then VEZ_Loader.h may be used to load the V-EZ entry points at runtime and no linker conflicts will exist.  You are right however that naming conflicts means VEZ.h and vulkan.h can not be included in the same source file.  As specified in our GPUOpen blog post as well as the github repo README.md, V-EZ is targeting specific ISVs who will unlikely be mixing native Vulkan with V-EZ.  The end goal with V-EZ is to allow ISVs in the professional graphics space to learn Vulkan semantics without all of the responsibility and complexity that comes with it.  This was the primary motivation behind retaining much of Vulkan's syntax.  There many existing Vulkan frameworks and wrappers which declare everything within a namespace with unique function and structure declarations, and if that is preferred that is certainly an alternative for developers not being targeted by V-EZ.

**Comment by marti4d** [comment]
Alright well good-to-know the answer is "Don't use this middleware". Thank you for making the decision easy. Seems super-logical to put it on GPUOpen when it's not actually open-source and isn't intended to be used by anyone but a select group of people :+1:

**Comment by marti4d** [comment]
Why bother releasing this software on GPUOpen if it's only targeting a select small group of ISVs? You're basically ensuring that some ISVs will consider this a no-go, since the naming conflicts would make it painful for them to "gradually" transition their app from OpenGL to Vulkan through this API.
