### ISSUE TITLE
Why no comments?

### ISSUE THREAD

**Issue by TechnikEmpire** [GPUOpen-LibrariesAndSDKs/V-EZ#58]
Having a quick look at the source code, I see no comments. It's setting the bar pretty high for contributions when there isn't any guidance anywhere on anything.

**Comment by manhnt9** [comment]
Have you checked out the documentation? It's in README file: https://gpuopen-librariesandsdks.github.io/V-EZ/

Well @soconne I think that you could consider adding this link to repository's description so people would easily catch it. I missed the link at first too.

**Comment by TechnikEmpire** [comment]
I saw the documentation, I'm just talking about comments in the code.
